{{
config(
materialized='incremental',
unique_key='PK_ODS_ES_STABLEX_CLIENT_ID',
merge_no_update_columns = ['SYS_CREATE_DTM'],
tags=["ods","es-eqai","scheduled-nightly"]
)
}}
-- Read the data from staging table as incrementally
with CTE_source as (
select
*
from {{ source('STAGING', 'STG_ES_STABLEX_CLIENT') }}
{% if is_incremental() %}
where SF_INSERT_TIMESTAMP > '{{ get_max_event_time('SF_INSERT_TIMESTAMP',not_minus3=True) }}'
{% endif %}
)
-- Apply deduplication logic
, CTE_dedup as (
select *
from CTE_source
qualify row_number() over (partition by NUM_CLIENT order by DATE_MODFC desc, SF_INSERT_TIMESTAMP desc) = 1
)

-- Create a batch id
, CTE_ins_batch_id as (
select TO_NUMBER(TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISSFF3')) as ins_batch_id
)
-- Create the final table
, CTE_final as (
select
{{ generate_surrogate_key(['NUM_CLIENT']) }} as PK_ODS_ES_STABLEX_CLIENT_ID,
CURRENT_TIMESTAMP as SYS_CREATE_DTM,
CTE_ins_batch_id.ins_batch_id as SYS_EXEC_ID,
CURRENT_TIMESTAMP as SYS_LAST_UPDATE_DTM,
NUM_CLIENT,
NOM_CLIENT as CLIENT_NAME,
NOM_LEGAL_CLIENT as LEGAL_CLIENT_NAME,
TYPE_COMPG as COMPANY_TYPE,
ADR_CLIENT_1 as CLIENT_ADDRESS_1,
ADR_CLIENT_2 as CLIENT_ADDRESS_2,
NOM_VILLE as CITY_NAME,
CODE_POSTAL_CLIENT as CLIENT_POSTAL_CODE,
STATUT_CLIENT as CLIENT_STATUS,
DATE_MODFC_STATUT as STATUS_MODIFICATION_DATE,
DATE_CREAT_CLIENT as CLIENT_CREATION_DATE,
CODE_LANGUE as LANGUAGE_CODE,
POURC_ESCOM as DISCOUNT_PERCENTAGE,
NBR_JOUR_ESCOM as DISCOUNT_DAYS,
TERME_PAIEM as PAYMENT_TERMS,
NUM_TAXE_PROVN as PROVINCIAL_TAX_NUMBER,
NUM_TAXE_FEDRL as FEDERAL_TAX_NUMBER,
ANNEE_INCOR as INCORPORATION_YEAR,
ANNEE_PRESENT_CONTR as CONTRACT_PRESENTATION_YEAR,
COMNT_CLIENT as CLIENT_COMMENT,
IND_APPL_CREDIT as CREDIT_APPLICATION_INDICATOR,
DATE_APPL_CREDIT as CREDIT_APPLICATION_DATE,
LIMITE_CREDIT as CREDIT_LIMIT,
IND_LETTRE_CREDIT as CREDIT_LETTER_INDICATOR,
DATE_RAPPORT_DB as DB_REPORT_DATE,
DELAIS_PAIEM_DB as DB_PAYMENT_DELAY,
DATE_DELAIS_DB as DB_DELAY_DATE,
IND_CONTRAT_SIGNE as SIGNED_CONTRACT_INDICATOR,
SECTR_ACTIV as ACTIVITY_SECTOR,
DATE_DERN_FACTURE as LAST_INVOICE_DATE,
IND_RECU_CREDIT as CREDIT_RECEIVED_INDICATOR,
USER_MODFC as MODIFICATION_USER,
DATE_MODFC as MODIFICATION_DATE,
DEVCLE as CURRENCY_KEY,
CODE_CONDITION as CONDITION_CODE,
CODE_MESSAGE as MESSAGE_CODE,
CODE_REPRS_CLIENT as CLIENT_REPRESENTATIVE_CODE,
CODE_MAISON_MERE as PARENT_COMPANY_CODE,
CODE_REPRS_VENTES as SALES_REPRESENTATIVE_CODE,
ABREV_REGION as REGION_ABBREVIATION,
COTE_CREDIT_DB as DB_CREDIT_RATING,
ABREV_PAYS as COUNTRY_ABBREVIATION,
ABREV_PROVN_ETAT as PROVINCE_STATE_ABBREVIATION,
DATE_DELAIS_STABLEX as STABLEX_DELAY_DATE,
DATE_HAUT_CREDIT as HIGH_CREDIT_DATE,
DELAIS_PAIEM_STABLEX as STABLEX_PAYMENT_DELAY,
HAUT_CREDIT as HIGH_CREDIT,
IND_FRAIS as FEE_INDICATOR,
IND_FRAIS_MIN as MINIMUM_FEE_INDICATOR,
NOM_GROUPE as GROUP_NAME,
RECYCLEUR as RECYCLER,
SOLDE_CLIENT as CLIENT_BALANCE,
TPS as GST,
TVQ as QST,
NUM_CLIENT_CIE as COMPANY_CLIENT_NUMBER,
CLCCPTCAR as CLCCPTCAR,
CLCCPTCAR_SAP as CLCCPTCAR_SAP,
CLCUNACAR as CLCUNACAR,
CLCUNACAR_SAP as CLCUNACAR_SAP,
LBQCPTENC as LBQCPTENC,
LBQCPTENC_SAP as LBQCPTENC_SAP,
CLCUNAENC as CLCUNAENC,
CLCUNAENC_SAP as CLCUNAENC_SAP,
CLCCPTESC as CLCCPTESC,
CLCCPTESC_SAP as CLCCPTESC_SAP,
CLCUNAESC as CLCUNAESC,
CLCUNAESC_SAP as CLCUNAESC_SAP,
IND_DOC_TAXATION as TAXATION_DOCUMENT_INDICATOR,
DATE_TRANSFERT_SAP as SAP_TRANSFER_DATE,
CLIENT_INTERNE as INTERNAL_CLIENT,
ETAT_COMPTE as ACCOUNT_STATUS,
CARTE_CREDIT as CREDIT_CARD,
TERME_PAIEM_SOLOMON as SOLOMON_PAYMENT_TERMS,
CODE_CL_CAT as CL_CATEGORY_CODE,
USER_MODFC_STATUT as STATUS_MODIFICATION_USER,
DATE_SOLDE as BALANCE_DATE,
TVQ_EXCEPTION_TRANSPORT as TRANSPORT_QST_EXCEPTION,
AX_ID as AX_ID,
AX_INVOICE_CUSTOMER_ID as AX_INVOICE_CUSTOMER_ID,
AX_BILLING_ADDRESS as AX_BILLING_ADDRESS,
AX_PHYSICAL_ADDRESS as AX_PHYSICAL_ADDRESS,
AX_PHYSICAL_CITY as AX_PHYSICAL_CITY,
AX_PHYSICAL_STATE as AX_PHYSICAL_STATE,
AX_PHYSICAL_COUNTRY as AX_PHYSICAL_COUNTRY,
PHONE_NUMBER as PHONE_NUMBER,
FAX_NUMBER as FAX_NUMBER,
NAICS_CODE as NAICS_CODE,
CUSTOMER_TYPE as CUSTOMER_TYPE,
CUSTOMER_WEBSITE as CUSTOMER_WEBSITE,
AX_PHYSICAL_CUSTOMER_NAME as AX_PHYSICAL_CUSTOMER_NAME,
AX_PHYSICAL_ZIP as AX_PHYSICAL_ZIP,
AX_TRANSFER_STATUS as AX_TRANSFER_STATUS,
TYPE_ENVOI_FACT as INVOICE_SENDING_TYPE,
ADR_ELECT_CC_FACT as INVOICE_CC_EMAIL_ADDRESS,
SUJET_FACT_ELECT as ELECTRONIC_INVOICE_SUBJECT,
CONTENU_FACT_ELECT as ELECTRONIC_INVOICE_CONTENT,
COMMENTAIRE_TYPE_ENVOI as SENDING_TYPE_COMMENT,
DATE_TYPE_ENVOI as SENDING_TYPE_DATE,
CLIENT_LAB as LAB_CLIENT,
SF_INSERT_TIMESTAMP
from CTE_dedup
join CTE_ins_batch_id on 1=1
)
select * from CTE_final